site_name: Scoutify
nav:
  - Home: index.md
  - API Reference: reference.md
  - About: about.md
  - Support: support.md
  - Contribute: contribute.md
  - License: license.md

theme:
  name: "material"
  palette:
    scheme: slate
    primary: teal
    accent: purple

extra_css:
  - css/mkdocstrings.css

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
      watch:
        - scoutify